import React, { useState } from 'react';
import { generateArchAdvice } from '../services/geminiService';
import { Cpu, Server, Globe, Database, ArrowRight, Loader2, AlertCircle, Terminal, CheckCircle2 } from 'lucide-react';

export const TechAdvisor: React.FC = () => {
  const [idea, setIdea] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);

  const handleAnalyze = async () => {
    if (!idea.trim()) return;
    setLoading(true);
    setResult(null);
    try {
      const data = await generateArchAdvice(idea);
      setResult(data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="py-24 bg-slate-900 relative overflow-hidden border-t border-slate-800">
      {/* Background Grid */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:40px_40px]"></div>

      <div className="max-w-7xl mx-auto px-6 lg:px-8 relative z-10">
        <div className="grid lg:grid-cols-2 gap-16 items-start">
          
          {/* Input Section */}
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand-900/50 border border-brand-500/30 text-brand-400 text-xs font-bold uppercase tracking-wider mb-6">
              <Cpu className="w-4 h-4" />
              AI Solutions Architect
            </div>
            
            <h2 className="text-3xl md:text-5xl font-bold text-white mb-6">
              Get an Instant <br/>
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-400 to-indigo-400">
                Technical Blueprint
              </span>
            </h2>
            
            <p className="text-slate-400 text-lg mb-8 leading-relaxed">
              Not sure which technologies to use? Describe your project idea below, and our AI Architect will recommend the optimal enterprise stack and execution strategy.
            </p>

            <div className="bg-slate-800/50 border border-slate-700 rounded-2xl p-6 backdrop-blur-sm shadow-xl">
              <textarea 
                value={idea}
                onChange={(e) => setIdea(e.target.value)}
                placeholder="e.g. I want to build a real-time delivery tracking app like Uber Eats but for pharmacy prescriptions..."
                className="w-full h-32 bg-slate-900/50 border border-slate-700 rounded-xl p-4 text-white placeholder-slate-500 focus:ring-2 focus:ring-brand-500 focus:border-transparent transition-all resize-none mb-4 font-mono text-sm"
              />
              <button 
                onClick={handleAnalyze}
                disabled={loading || !idea.trim()}
                className="w-full py-4 bg-brand-600 hover:bg-brand-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold rounded-xl transition-all flex items-center justify-center gap-2 shadow-lg shadow-brand-900/50"
              >
                {loading ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    Analyzing Requirements...
                  </>
                ) : (
                  <>
                    <Terminal className="w-5 h-5" />
                    Generate Architecture
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Result Section */}
          <div className="relative min-h-[400px]">
            {result ? (
              <div className="bg-slate-800 border border-slate-700 rounded-2xl p-8 shadow-2xl animate-in fade-in slide-in-from-bottom-8 duration-700">
                <div className="flex items-center gap-3 mb-6 pb-6 border-b border-slate-700">
                  <div className="p-2 bg-green-500/10 rounded-lg">
                    <CheckCircle2 className="w-6 h-6 text-green-400" />
                  </div>
                  <div>
                    <h3 className="text-white font-bold text-lg">Analysis Complete</h3>
                    <p className="text-slate-400 text-xs uppercase tracking-wider">Generated by Gemini Pro</p>
                  </div>
                </div>

                <div className="space-y-6">
                  <div>
                    <h4 className="text-brand-400 text-xs font-bold uppercase tracking-widest mb-3">Executive Summary</h4>
                    <p className="text-slate-300 text-sm leading-relaxed border-l-2 border-brand-500 pl-4">
                      {result.brief}
                    </p>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="bg-slate-900/50 p-4 rounded-xl border border-slate-700/50">
                       <span className="text-slate-500 text-xs font-bold uppercase block mb-1">Complexity</span>
                       <span className={`font-bold ${
                         result.analysis.complexity === 'High' || result.analysis.complexity === 'Enterprise' ? 'text-orange-400' : 'text-white'
                       }`}>{result.analysis.complexity}</span>
                    </div>
                    <div className="bg-slate-900/50 p-4 rounded-xl border border-slate-700/50">
                       <span className="text-slate-500 text-xs font-bold uppercase block mb-1">Est. Timeline</span>
                       <span className="text-white font-bold">{result.analysis.estimatedDuration}</span>
                    </div>
                  </div>

                  <div>
                    <h4 className="text-brand-400 text-xs font-bold uppercase tracking-widest mb-3">Recommended Stack</h4>
                    <div className="grid gap-3">
                      <div className="flex items-center gap-3 text-sm text-slate-300">
                        <Globe className="w-4 h-4 text-indigo-400 shrink-0" />
                        <span className="font-mono text-xs bg-slate-900 px-2 py-1 rounded border border-slate-700 text-indigo-300">Frontend</span>
                        {result.stack.frontend}
                      </div>
                      <div className="flex items-center gap-3 text-sm text-slate-300">
                        <Server className="w-4 h-4 text-indigo-400 shrink-0" />
                        <span className="font-mono text-xs bg-slate-900 px-2 py-1 rounded border border-slate-700 text-indigo-300">Backend</span>
                        {result.stack.backend}
                      </div>
                      <div className="flex items-center gap-3 text-sm text-slate-300">
                        <Database className="w-4 h-4 text-indigo-400 shrink-0" />
                        <span className="font-mono text-xs bg-slate-900 px-2 py-1 rounded border border-slate-700 text-indigo-300">Data</span>
                        {result.stack.database}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="h-full border-2 border-dashed border-slate-800 rounded-2xl flex flex-col items-center justify-center text-center p-12">
                <div className="w-20 h-20 bg-slate-800 rounded-full flex items-center justify-center mb-6">
                  <Cpu className="w-10 h-10 text-slate-700" />
                </div>
                <h3 className="text-slate-600 font-bold text-xl mb-2">Awaiting Input</h3>
                <p className="text-slate-600 max-w-sm">
                  Describe your vision on the left to receive a professional architectural breakdown.
                </p>
              </div>
            )}
          </div>

        </div>
      </div>
    </div>
  );
};